### ISSUE TITLE
Please don't remove the mapping class

### ISSUE THREAD

**Issue by fnevgeny** [italiangrid/storm-puppet-module#9]
Hi,

Let's instead improve it. See the last entry in <https://ggus.eu/index.php?mode=ticket_info&ticket_id=148874>.

Thanks,
Evgeny

**Comment by fnevgeny** [comment]
Alternatively, perhaps this part could be converted into a separate puppet module.

**Comment by enricovianello** [comment]
Hi Evgeny,
I moved the mapping class into a separated module:
https://forge.puppet.com/cnafsd/lcmaps
I renamed it 'lcmaps'

Cheers,
Enrico

**Comment by enricovianello** [comment]
Thanks for the feedback on GGUS Ticket, I surely can add that change to the .erb template.
Maybe the same thing could be done for Capabilities. I'll evaluate and eventually add this little changes.
Thanks again for the feedback.

Enrico

**Comment by fnevgeny** [comment]
Thanks, Enrico! Eventually, I'm looking forward to being able to configure entire cluster using puppet and ditching yaim.

**Comment by fnevgeny** [comment]
PS. The project URL in puppet forge points to <https://github.com/italiangrid/puppet-lcmaps>; do you plan to move it there from your personal git? Also, I've just found another module under the same name, <https://github.com/unlhcc/puppet-lcmaps>.

**Comment by enricovianello** [comment]
My fault, I moved the repository at https://github.com/italiangrid/puppet-lcmaps as pointed by the module. Thanks

**Comment by fnevgeny** [comment]
OK, closing this ticket; will submit further issues to puppet-lcmaps :).
